### PR TITLE
PR- update db model file for tsfm service

### PR DESCRIPTION
**Pull request by chliuhelmut**
create  following tables  

device_data
device_info
user_mgmt
rules
notifications
posts

### CODE REVIEW

**Comment by chliuhelmut** [comment]
good to go

**Review by chliuhelmut — COMMENTED** [review]
good to go

**Review by chliuhelmut — COMMENTED** [review]
ok

**Review by chiiiiizz — APPROVED** [review]

**Review by chiiiiizz — APPROVED** [review]

**Review by chiiiiizz — APPROVED** [review]

**Review by chiiiiizz — APPROVED** [review]

**Review by chliuhelmut — COMMENTED** [review]
add webhook service status to update data to table  user_mgmt and device_info

**Pull request merged**
